// ============================================================
// services/pdfService.js — PDF Report Generator
// Generates monthly/yearly financial reports using PDFKit
// ============================================================

const PDFDocument = require("pdfkit");

/**
 * generateMonthlyPDF
 * Creates a styled PDF report with financial summary
 * @param {Object} data - Report data
 * @returns {Buffer} PDF buffer
 */
const generateMonthlyPDF = (data) => {
  return new Promise((resolve, reject) => {
    const buffers = [];
    const doc = new PDFDocument({ margin: 50, size: "A4" });

    // Collect PDF chunks into a buffer
    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    const { user, period, totalIncome, totalExpenses, balance, savingsRate, categoryBreakdown, transactions } = data;

    // ── Header ────────────────────────────────────────────────
    doc
      .fillColor("#6366f1")
      .fontSize(28)
      .font("Helvetica-Bold")
      .text("AiXpense", 50, 50);

    doc
      .fillColor("#1e293b")
      .fontSize(16)
      .font("Helvetica")
      .text(`Financial Report — ${period}`, 50, 85);

    doc
      .fillColor("#64748b")
      .fontSize(11)
      .text(`Generated for: ${user.name} (${user.email})`, 50, 105)
      .text(`Generated on: ${new Date().toLocaleDateString("en-IN")}`, 50, 120);

    // Divider
    doc.moveTo(50, 140).lineTo(545, 140).strokeColor("#e2e8f0").stroke();

    // ── Summary Cards ─────────────────────────────────────────
    doc.moveDown(2);

    const cardY = 160;
    const drawCard = (x, y, label, value, color) => {
      doc.roundedRect(x, y, 150, 70, 8).fillColor(color).fill();
      doc.fillColor("white").fontSize(10).text(label, x + 10, y + 12);
      doc.fillColor("white").fontSize(18).font("Helvetica-Bold").text(value, x + 10, y + 28);
    };

    drawCard(50, cardY, "Total Income", `₹${totalIncome.toLocaleString("en-IN")}`, "#10b981");
    drawCard(220, cardY, "Total Expenses", `₹${totalExpenses.toLocaleString("en-IN")}`, "#ef4444");
    drawCard(390, cardY, "Net Balance", `₹${balance.toLocaleString("en-IN")}`, "#6366f1");

    // ── Savings Rate ──────────────────────────────────────────
    doc.fillColor("#1e293b").font("Helvetica-Bold").fontSize(12).text(
      `Savings Rate: ${savingsRate.toFixed(1)}%`,
      50,
      cardY + 90
    );

    // Divider
    doc.moveTo(50, cardY + 115).lineTo(545, cardY + 115).strokeColor("#e2e8f0").stroke();

    // ── Category Breakdown ────────────────────────────────────
    doc.fillColor("#1e293b").font("Helvetica-Bold").fontSize(14).text(
      "Spending by Category",
      50,
      cardY + 130
    );

    let catY = cardY + 158;
    const sortedCategories = Object.entries(categoryBreakdown)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 10); // top 10

    sortedCategories.forEach(([category, amount]) => {
      const pct = totalExpenses > 0 ? ((amount / totalExpenses) * 100).toFixed(1) : 0;
      const barWidth = totalExpenses > 0 ? (amount / totalExpenses) * 300 : 0;

      doc.fillColor("#64748b").font("Helvetica").fontSize(10).text(category, 50, catY);
      doc.fillColor("#94a3b8").fontSize(10).text(`₹${amount.toLocaleString("en-IN")} (${pct}%)`, 380, catY);

      // Progress bar
      doc.roundedRect(50, catY + 14, 300, 6, 3).fillColor("#e2e8f0").fill();
      doc.roundedRect(50, catY + 14, Math.max(barWidth, 2), 6, 3).fillColor("#6366f1").fill();

      catY += 34;
    });

    // ── Recent Transactions ───────────────────────────────────
    if (catY < 600 && transactions && transactions.length > 0) {
      doc.moveTo(50, catY + 10).lineTo(545, catY + 10).strokeColor("#e2e8f0").stroke();
      doc.fillColor("#1e293b").font("Helvetica-Bold").fontSize(14).text("Recent Transactions", 50, catY + 20);

      let txY = catY + 45;
      transactions.slice(0, 10).forEach((tx) => {
        doc.fillColor("#1e293b").font("Helvetica").fontSize(10)
          .text(tx.description || tx.category, 50, txY)
          .text(new Date(tx.date).toLocaleDateString("en-IN"), 300, txY)
          .fillColor("#ef4444")
          .text(`-₹${tx.amount.toLocaleString("en-IN")}`, 450, txY);
        txY += 20;
        if (txY > 750) return; // prevent overflow
      });
    }

    // ── Footer ────────────────────────────────────────────────
    doc.fillColor("#94a3b8").fontSize(9).text(
      "Generated by AiXpense — Your AI-powered expense management platform",
      50,
      780,
      { align: "center", width: 495 }
    );

    doc.end();
  });
};

module.exports = { generateMonthlyPDF };
